name: Build ROS 2 Workspace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # GitHub Actionsからリポジトリのコードを取得する
      - name: Check out code
        uses: actions/checkout@v2

      # ROS 2のセットアップ
      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.1
        with:
          ros-distro: foxy
          package-name: 'desktop'   # 必要に応じて 'desktop' を変える

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-vcstool
          sudo rosdep init
          rosdep update

      # ワークスペースのビルド
      - name: Build ROS 2 Workspace
        run: |
          cd ~/ros2_ws
          colcon build --symlink-install

