name: Build ROS 2 Workspace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.1
        with:
          use-ros2-testing: true  # 正しい引数を設定

      - name: Add ROS 2 Repositories
        run: |
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo bash -c "echo 'deb http://packages.ros.org/ros/ubuntu focal main' > /etc/apt/sources.list.d/ros-latest.list"
          sudo bash -c "echo 'deb http://packages.ros.org/ros2-testing/ubuntu focal main' > /etc/apt/sources.list.d/ros2-latest.list"
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-vcstool
          sudo rosdep init
          rosdep update

      - name: Build ROS 2 Workspace
        run: |
          cd ~/ros2_ws
          colcon build --symlink-install

