name: ROS 2 Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ros-distro: [foxy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.1
        with:
          use-ros2-testing: true
          ros-distro: foxy

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-vcstool

      - name: Build and test
        run: |
          source /opt/ros/foxy/setup.bash
          colcon build
          colcon test --packages-select clock
          colcon test-result --verbose

